Title =  "Bunny's website."
BaseUrl = "https://yinan-hong.github.io/"
publishdir = "/public"

DefaultContentLanguage = "zh-cn"
LanguageCode = "zh-CN"

hasCJKLanguage = true

Theme =  "hugo-theme-next-main"

busuanzi = true

MetaDataFormat =  "toml"

PaginatePath =  "p"
Paginate = 6

DisablePathToLower =  false

PreserveTaxonomyNames = false

enableRobotsTXT = true
enableEmoji = true

timeout = 100000
ignoreErrors = ["error-remote-getjson"]

[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/xml"
    baseName = "searchindex"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true


[markup]

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      lineNos = true
      style = "github"