[TagsCloud]
  Enable = true
  Limit = 10

[Share]
  Enable = true
  AddthisId = "ra-6091f652e3a51633"

[Comment]
  Enable = true
  Module = "Waline"
  LiveReId = "Your LiveReId"
  WalineSerURL = "https://waline-three.vercel.app/"

[LeanCloud]
  AppId = "zW8JImTBYzSSqrOBJBIKuG2l-MdYXbMMI"
  AppKey = "kn6XMgXB7RADF5jYtYyW6TPU"
  ServerURL = "zw8jimtb.api.lncldglobal.com"

[Statis]
  BusuanziCounter = true
  CNNZSiteId = "1279899318"
  BaiduSiteId = "Your BaiduSiteId"
  GoogleSiteId = "Your GoogleSiteId"

[OnlineIM]
  Enable = false
  DaoVoiceId = "Your DaoVoiceId"

[Others]
  RevolverMapId = "Your RevolverMapId"